### ISSUE TITLE
Negative Sample Sampling Strategy

### ISSUE THREAD

**Issue by liangchild** [minjoong507/BM-DETR#6]
Thank you very much for your work.

I saw in the paper that there are two guiding principles for Sampling Strategy. But in the code, negative samples seem to only require not being in the same video.

I hope you can answer my questions. Thank you again for your work.

**Comment by minjoong507** [comment]
Hi @liangchild,

First, thank you for your interest in our work.

Sorry for the inconvenience. As you mentioned, the codes will sample negative queries from the same video if the annotation file doesn't have the key `neg_query_ids`. 

It's been a while since I worked on this work, so I'll let you know after checking the file.

https://github.com/minjoong507/BM-DETR/blob/f9ba27211ae468cdda2ce5d946b0c7b2fe4b6464/bm_detr/start_end_dataset.py#L138-L150

Also, you can construct negative samples using [SentenceBERT](https://github.com/UKPLab/sentence-transformers) and save them in the annotation file yourself, as we did.

Thank you :)

Minjoon.
